### ISSUE TITLE
Cannot build and test worlds

### ISSUE THREAD

**Issue by dav64** [Bartkk0/VRCSDKonLinux#4] opened 2022-02-14 20:52 UTC
Hi,

Applied the GUIDPatch + vrchat.exe script

At the moment, I manually rename lowercased world in /tmp and publish it to test it but its sooo long and cumbersome

Got the following exception:

```
Export Exception - System.IO.FileNotFoundException: /tmp/DefaultCompany/Test World/scene-StandaloneWindows64-SampleScene.vrcw does not exist
File name: '/tmp/DefaultCompany/Test World/scene-StandaloneWindows64-SampleScene.vrcw'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x000b6] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at VRC.SDK3.Editor.Builder.VRCWorldAssetExporter.ExportCurrentSceneResource () [0x00254] in <f06bb742fa724b42879c52360488bb7f>:0 
UnityEngine.Debug:LogError (object)
VRC.SDK3.Editor.Builder.VRCWorldAssetExporter:ExportCurrentSceneResource ()
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportSceneResource ()
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportSceneResourceAndRun ()
VRC.SDKBase.Editor.VRC_SdkBuilder:ExportSceneResourceAndRun ()
```

Any ideas ?

**Comment by Bartkk0** [comment] 2022-03-05 15:41
Couldn't reproduce it, maybe try to reimport the SDK and try the updated vrchat.exe script, also you don't need the GUIDPatch to make it work for worlds.

**Comment by Bartkk0** [comment] 2023-03-02 00:43
Fixed with the new update

**Closed by Bartkk0** 2023-03-02 00:43 UTC
